#define NOTENUM_C3 48
#define NOTENUM_D3 50
#define NOTENUM_E3 52

// drum note numbers
#define NOTENUM_SNARE_RIM 40
#define NOTENUM_TOM1_RIM 50
#define NOTENUM_TOM2_RIM 47
#define NOTENUM_TOM3_RIM 58
#define NOTENUM_HHAT_OPEN_RIM 26
#define NOTENUM_HHAT_CLOSED_RIM 22
#define NOTENUM_CRASH1_RIM 55
#define NOTENUM_RIDE_RIM 52
#define NOTENUM_CRASH2_RIM 59

#define NOTENUM_KICK_HEAD 36
#define NOTENUM_SNARE_HEAD 38
#define NOTENUM_TOM1_HEAD 48
#define NOTENUM_TOM2_HEAD 45
#define NOTENUM_TOM3_HEAD 43
#define NOTENUM_HHAT_OPEN_HEAD 46
#define NOTENUM_HHAT_CLOSED_HEAD 42
#define NOTENUM_CRASH1_HEAD 49
#define NOTENUM_RIDE_HEAD 57
#define NOTENUM_CRASH2_HEAD 51

// drum led count
#define NUM_LEDS_TEST 5
#define NUM_LEDS_KICK 30
#define NUM_LEDS_SNARE 48
#define NUM_LEDS_TOM1 38
#define NUM_LEDS_TOM2 38
#define NUM_LEDS_TOM3 38
#define NUM_LEDS_HHAT 14
#define NUM_LEDS_CRASH1 13
#define NUM_LEDS_CRASH2 14
#define NUM_LEDS_RIDE 15
