#define NOTENUM_KICK 33
#define NOTENUM_SNARE 38
#define NOTENUM_TOM1 48
#define NOTENUM_TOM2 45
#define NOTENUM_TOM3 41
#define NOTENUM_HHAT_OPEN 51
#define NOTENUM_HHAT_CLOSED 22
#define NOTENUM_CRASH1 49
#define NOTENUM_RIDE 51
#define NOTENUM_CRASH2 49

// drum led count
#define NUM_LEDS_KICK 30
#define NUM_LEDS_SNARE 48
#define NUM_LEDS_TOM1 38
#define NUM_LEDS_TOM2 38
#define NUM_LEDS_TOM3 38
#define NUM_LEDS_HHAT 14
#define NUM_LEDS_CRASH1 13
#define NUM_LEDS_CRASH2 14
#define NUM_LEDS_RIDE 15
